version: 2
updates:
  # Enable version updates for Ruby dependencies
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "saturnflyer"
    assignees:
      - "saturnflyer"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "ruby"
    # Allow both direct and indirect dependency updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
